# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: false
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - libgsl0-dev
os:
  - linux
  - osx
